#TEMPLATE PARA EL TIPO DE SERVICIO: NODE PORT
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello
spec:
  replicas: 3
  selector:
    matchLabels:
      role: hello
  template:
    metadata:
      labels:
        role: hello
    spec:
      containers:
      - name: hello
        image: mariopalato/demo-kubernetes:latest
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: hello
spec:
  #NODE PORT
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    #OPCIÓN EXTRA PARA ESTE TIPO DE SERVICIO
    #SE ESPECIFA EL PUERTO QUE QUEREMOS QUE SE CREE EN CADA NODO PARA LLEGAR A NUESTRO SERVICIO
    nodePort: 30000
  selector:
    role: hello